slam_toolbox:
  ros__parameters:

    # Cấu hình Solver (Bộ giải)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Cấu hình Topic & Frame (QUAN TRỌNG)
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping # Chế độ vẽ bản đồ

    # Tần số cập nhật
    map_update_interval: 5.0
    transform_publish_period: 0.02 # 50Hz

    # Cấu hình bản đồ
    resolution: 0.05      # Độ phân giải (5cm/pixel)
    max_laser_range: 12.0 # Tầm xa tối đa của Lidar tin cậy được
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Cấu hình thuật toán khớp nối (Scan Matching)
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.3 # Đi 0.3m mới cập nhật map 1 lần
    minimum_travel_heading: 0.3  # Xoay 0.3 rad mới cập nhật map
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35   
    loop_match_minimum_response_fine: 0.45